### model
model_name_or_path: izzcw/mini_llama_crafting_sft_success_new_mem
trust_remote_code: true
deepspeed: examples/deepspeed/ds_z3_config.json

### method
stage: dpo
do_train: true
finetuning_type: full
# lora_rank: 8
# lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
push_to_hub: true

### dataset
dataset: crafting_dpo_pairs
template: llama3
cutoff_len: 8196
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/mini_dpo_crafting
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# eval_dataset: dpo_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
